version: '2'
services:
  jhipster-registry:
    container_name: jhipster-registry
    image: jhipster/jhipster-registry
    environment:
      - "SPRING_PROFILES=dev,native"
    ports:
      - "8761:8761"
    volumes:
      - ./central-server-config:/central-config
  gateway:
    container_name: gateway
    build: ./gateway/
    ports:
      - "8080:8080"
    links:
      - jhipster-registry:registry
    depends_on:
      - jhipster-registry
  app1-mysql:
    container_name: app1-mysql
    build: ./app1-mysql/
    ports:
      - "8081:8080"
    links:
      - jhipster-registry:registry
    depends_on:
      - jhipster-registry
  app2-postgres:
    container_name: app2-postgres
    build: ./app2-postgres/
    ports:
      - "8082:8080"
    links:
      - jhipster-registry:registry
    depends_on:
      - jhipster-registry
  app3-mongo:
    container_name: app3-mongo
    build: ./app3-mongo/
    ports:
      - "8083:8080"
    links:
      - jhipster-registry:registry
    depends_on:
      - jhipster-registry
#Centralized logging with ELK
  elk-elasticsearch:
    container_name: elk-elasticsearch
    image: elasticsearch:2.2.0
    ports:
      - "9200:9200"
      - "9300:9300"
  elk-logstash:
    container_name: elk-logstash
    image: logstash:2.2.2
    ports:
      - "5000:5000/udp"
    volumes:
      - ./log-monitoring/logconfig/:/config-dir
    command: logstash -f /config-dir/logstash.conf
    links:
      - elk-elasticsearch:elasticsearch
  elk-kibana:
    container_name: elk-kibana
    image: kibana:4.4.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elk-elasticsearch:9200
    links:
      - elk-elasticsearch:elasticsearch